### PR TITLE
Replace string dateformat functions with momentjs dateformat

### PR DESCRIPTION
**Pull request by TobiasWalle**
I had problems with the european dateformat "DD.MM.YYYY". In order to solve that issue I replaced the current implementation of the hard coded dateformats with the dateformats of [momentjs](http://momentjs.com/).

I also set the months as an input. This allows user to replace the month labels. This is necessary if you want to tranlate the values to other languages.

### CODE REVIEW

**Comment by koleary94** [comment]
thanks a lot @TobiasWalle ! going to review and merge soon

**Comment by koleary94** [comment]
hey @TobiasWalle . sorry for the late reply. this looks great! c?an you resolve the conflicts when you have a chance? then i'll merge

**Comment by TobiasWalle** [comment]
Hey @koleary94 
I'm glad you like my changes. I'm going to resolve the conflicts this weekend, so you can merge.

**Comment by koleary94** [comment]
thanks again @TobiasWalle! going to merge

**Pull request merged**
